---
title: "ststic-99"
#author: "gcook"
#date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

source memory would be color of the bars in a plot. Test format change may bias memory.

```{r}
setwd("C:/Users/gcook/Sync/Data/jurorthreshold")
library(magrittr)
library(dplyr)
```


```{r}
S99_5y <- data.frame(
  score = c(-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
  year = as.factor(rep(5, 14)),
  rate = c(3.8, 5.1, 6.9, 9.1, 12.0, 15.7, 20.3, 25.8, 32.1, 39.2, 46.8, 54.5, 62.0, 69.0),
  ci95_l = c(2.9, 4.0, 5.5, 7.6, 10.2, 13.6, 17.8, 22.9, 28.7, 35.2, 42.2, 49.4, 56.5, 63.3),
  ci95_u = c(5.0, 6.5, 8.5, 11.0, 14.2, 18.2, 23.0, 28.9, 35.7, 43.3, 51.4, 59.5, 67.2, 74.2),
  size = seq(1, 14*5, 5)-1
)

S99_10y <- data.frame(
  score = c(-3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
  year = as.factor(rep(10, 14)),
  rate = c(NA, NA, 14.4, 17.8, 21.8, 26.5, 31.7, 37.4, 43.4, 49.7, 56.0, 62.1, 67.8, 73.1),
  ci95_l = c(NA, NA, 10.6, 13.9, 17.9, 22.4, 27.2, 31.9, 36.6, 41.3, 45.9, 50.5, 55.0, 59.4),
  ci95_u = c(NA, NA,19.4, 22.6, 26.4, 31.0, 36.5, 43.1, 50.5, 58.2, 65.6, 72.5, 78.4, 83.4),
  size = c(NA, NA, seq(1, 12*5, 5)-1)
)

S99_10y <- S99_10y %>% dplyr::filter(score >= -1)
#S99_5y$score  <- rev(S99_5y$score) 
#S99_5y$rate   <- rev(S99_5y$rate) 
#S99_10y$score <- rev(S99_10y$score) 
#S99_10y$rate  <- rev(S99_10y$rate) 
#S99_10y$rate
#rev(S99_10y$rate)
#S99 <- rbind(S99_5y, S99_10y)
#
reduceBy = .5
# See table 2S for Blais, Babchishin, & Hanson (2021). Improving our Risk Communication: Standardized Risk Levels for BARR-2002R
BRENT <- data.frame(
  score = c(   rep(-2, 82*reduceBy), rep(-1, 17*reduceBy), 
               rep(0, 179*reduceBy), rep(1, 179*reduceBy), 
               rep(2, 251*reduceBy), rep(3, 156*reduceBy), 
               rep(4, 174*reduceBy), rep(5, 153*reduceBy), 
               rep(6, 150*reduceBy), rep(7, 111*reduceBy), rep(8, 6*reduceBy)),
  rate = c(
    rnorm(82*reduceBy, 1.3, 1), rnorm(17*reduceBy, 2.2, 1), 
    rnorm(179*reduceBy, 3.4, 2), rnorm(179*reduceBy, 5.7,  2), 
    rnorm(251*reduceBy, 9.0, 3), rnorm(156*reduceBy, 14, 3), 
    rnorm(174*reduceBy, 21.2, 4), rnorm(153*reduceBy, 30.6, 4), 
    rnorm(150*reduceBy, 42, 8), rnorm(111*reduceBy, 54.4, 8),     rep(NA, 6*reduceBy)),
  rate_bin = c(
    rbinom(82*reduceBy, size = 1, .013), rbinom(17*reduceBy, size = 1, .022), 
    rbinom(179*reduceBy, size = 1, .034), rbinom(179*reduceBy, size = 1, .057), 
    rbinom(251*reduceBy, size = 1, .09), rbinom(156*reduceBy, size = 1, .14), 
    rbinom(174*reduceBy, size = 1, .212), rbinom(153*reduceBy, size = 1, .306), 
    rbinom(150*reduceBy, size = 1, .42), rbinom(111*reduceBy, size = 1, .544), hhhhrep(NA, 6*reduceBy))
)
#BRENT
#write.csv(BRENT, "BRENT_2y_obs.csv")
BRENT <- read.csv("BRENT_2y_obs.csv")

BRENT %>% group_by(., score) %>% summarise(mean(rate))
BRENT_2 <- BRENT %>% filter(score %in% c(2))
BRENT_2 %>% summarise(mean(rate)) 
BRENT_2
# Mr. Brent

BRENT_2.p <- BRENT_2 %>%
  ggplot(data = ., aes(x = score, y = rate)) +
  #geom_line(size = .25) + 
  geom_point(size = 2, alpha = .5, 
             position = position_jitter(seed = 42, width = 1)) +
  #geom_point(aes(size = rate), alpha = .5, position = position_jitter(seed = 42, width = 1)) +
  theme_classic() + #minimal() + 
  theme(axis.line = 
          element_line(colour = "black", 
                       size = 1, linetype = "solid"),
        axis.title = element_text(size = 14, face = "bold"), 
        axis.text  = element_text(size = 14),
        strip.text.y = element_text(size = 12),
        aspect.ratio = 1/1,
        legend.position = "none"
        ) +
    scale_x_discrete(
      name   = "Static-99R Score = 2" #, limits = 2
    ) +
    scale_y_continuous(
      # position = "right",
      name = "Predicted Recidivism Rate (%)", 
      limits = c(0, 20),    #  n.breaks = 50
      breaks = seq(0, 20, 1)
    ) +
  ggtitle(""); BRENT_2.p


#ggplot(data = BLAIS_2y_obs, aes(x = score, y = rate_bin)) + 
#  geom_jitter(height = .05) + theme_classic()
 
```


```{r}
reduceBy = .10
BLAIS_2y_obs <- data.frame(
  score = c(   rep(-2, 82*reduceBy), rep(-1, 17*reduceBy), 
               rep(0, 179*reduceBy), 
               rep(1, 179*reduceBy), rep(2, 251*reduceBy), 
               rep(3, 156*reduceBy), 
               rep(4, 174*reduceBy), rep(5, 153*reduceBy), 
               rep(6, 150*reduceBy),
               rep(7, 111*reduceBy), rep(8, 6*reduceBy)),
  rate = c(
    rnorm(82*reduceBy, 1.3, 1),
    rnorm(17*reduceBy, 2.2, 1), 
    rnorm(179*reduceBy, 3.4, 2), 
    rnorm(179*reduceBy, 5.7,  2), 
    rnorm(251*reduceBy, 9.0, 3), 
    rnorm(156*reduceBy, 14, 3), 
    rnorm(174*reduceBy, 21.2, 4), 
    rnorm(153*reduceBy, 30.6, 4), 
    rnorm(150*reduceBy, 42, 8),
    rnorm(111*reduceBy, 54.4, 8), 
    rep(NA, 6*reduceBy)),
  rate_bin = c(
    rbinom(82*reduceBy, size = 1, .013),
    rbinom(17*reduceBy, size = 1, .022), 
    rbinom(179*reduceBy, size = 1, .034), 
    rbinom(179*reduceBy, size = 1, .057), 
    rbinom(251*reduceBy, size = 1, .09), 
    rbinom(156*reduceBy, size = 1, .14), 
    rbinom(174*reduceBy, size = 1, .212), 
    rbinom(153*reduceBy, size = 1, .306), 
    rbinom(150*reduceBy, size = 1, .42),
    rbinom(111*reduceBy, size = 1, .544), 
    rep(NA, 6*reduceBy))
)

#write.csv(BLAIS_2y_obs, "BLAIS_2y_obs.csv")
BLAIS_2y_obs <- read.csv("BLAIS_2y_obs.csv")
BLAIS_2y_obs$rate_z <- as.numeric(scale(BLAIS_2y_obs$rate))

# remove the NAs in score 8
BLAIS_2y_obs <- BLAIS_2y_obs %>% dplyr::filter(score < 8)
mean(BLAIS_2y_obs$score, na.rm = T)
mean(BLAIS_2y_obs$rate, na.rm = T)

# Mr. Brent
BLAIS_2y_obs %>% 
  mutate(., cnt = 1) %>%
  mutate(., total = sum(cnt)) %>%
  group_by(., score) %>% 
  summarise(prob = sum(cnt)/mean(total))



Blais.p <- ggplot(data = BLAIS_2y_obs, 
                  mapping = aes(x = score, y = rate
                                , #alpha = rate
                                )) +
  # for wai1, size 2, width was .7; .3 for wai2, alpha = .5
#  geom_point(size = 2, 
#             alpha = .5, 
#             position = position_jitter(seed = 68, width = .3)) +
  geom_point(aes(#size = rate,
                 alpha = rev(rate_z)
                 ), 
             #alpha = .5, 
             position = position_jitter(seed = 68, width = .3)) + 
  #geom_line(size = .25) + 
  theme_classic() + #minimal() + 
  theme(axis.line = 
          element_line(colour = "black", 
                       size = 1, linetype = "solid"),
        axis.title = element_text(size = 14, face = "bold"), 
        axis.text  = element_text(size = 14),
        strip.text.y = element_text(size = 12),
        aspect.ratio = 1/1,
        legend.position = "none"
        ) +
    scale_x_discrete(
      name   = "Static-99R Score", limits = seq(-2, 7)
    ) +
    scale_y_continuous(
      # position = "right",
      name = "Predicted Recidivism Rate (%)", 
      limits = c(0, 75),    #  n.breaks = 50
      breaks = seq(0, 75, 5)
    ); Blais.p
  
BLAIS_2y_obs %>%
  group_by(., score) %>%
  count(.)

density(BLAIS_2y_obs$score) %>% plot()

```

```{r}
# Phenix, Helmus, & Hanson, 2016, low, 13%; low‐mod, 21%; mod‐high, 30%; high, 43%)

library(ggplot2)
#library(grid)
#library(pBrackets)


?sample
x = c(30, 35, 40, 45, 50, 55, 60) #, 95, 100); 
y = x * sample(c(.9, .95, 1, 1.1, 1.2, 1.25, 1.3), length(x))
y = c(57.0, 65.0, 87.25, 67.5, 96.0, 93.5, 117.0)
#               (c(60, 65, 70, 75, 80, 85, 90) *1000)
#sample(x) * 1000
CORDAT <- data.frame(City = c("Austin", "Philadelphia", "Kansas City", 
                              "Tampa", "Jersey City", "Omaha", 
                              "Athens"),
                     age = x,
                     income = y*1000)
CORDAT %>% 
  dplyr::arrange(., City) %>%
  kbl_it()

CORDAT %>% 
  ggplot(data = ., aes(x = age, y = income)) + 
  geom_point() + theme_classic() 

CORDAT %>% 
  cor.test(~ age+income, data = .) %>% 
  broom::tidy(.) %>% select(., estimate) %>% as.numeric()


p <- ggplot(S99_10y, aes(x = score, y = rate)) +
  geom_line(size = .25) + 
  geom_point(aes(size = rate)) + 
  #geom_point(aes(size = rev(rate)), alpha = .7) +
  #geom_point(aes(y = ci95_l, size = rev(rate)), alpha = .7) +
  #geom_point(aes(y = ci95_u, size = rev(rate)), alpha = .7) +
  #geom_point(color = "black") +
  theme_classic() + #minimal() + 
  theme(axis.line = 
          element_line(colour = "black", 
                       size = 1, linetype = "solid"),
        axis.title = element_text(size = 14, face = "bold"), 
        axis.text  = element_text(size = 14),
        strip.text.y = element_text(size = 12),
        aspect.ratio = 1/1,
        legend.position = "none"
        ) +
  scale_x_discrete(
    name   = "Static-99R Score", limits = seq(-1, 10)
    ) +
  scale_y_continuous(
   # position = "right",
    name = "Predicted Recidivism Rate (%)", 
    limits = c(5, 100),
    breaks = seq(5, 100, 5)
    ); p


vertical <- p + 
  annotate("text", x = -1, y = 5, label = "low", angle = 90) +
  annotate("text", x = 1.5,y=11, label = "moderate", angle = 90) +
  annotate("text", x = 7.5, y = 6, label = "high", angle = 90) + 
  geom_vline(xintercept = -.5, linetype = 2) +
  geom_vline(xintercept = 3.5, linetype = 2) ; vertical

horizontal <- p +
  annotate("text", x = 8, y = 8, label = "low risk", angle = 0) +
  annotate("text", x = 8, y = 25,label="moderate risk", angle = 0) +
  annotate("text", x = 8, y = 45, label = "high risk", angle = 0) + 
  geom_hline(yintercept = 15, linetype = 2) +
  geom_hline(yintercept = 35, linetype = 2) ; horizontal

p
geom_vline(xintercept = -1, , color = "red") +
    annotate(geom = "text", x = -1, y = -1, label = "Helpful annotation", color = "red",
             angle = 90)


grid.locator(unit = "native") 
bottom_y <- 284 
grid.brackets(220, bottom_y,   80, bottom_y, lwd=2, col="red")
grid.brackets(600, bottom_y,  440, bottom_y, lwd=2, col="red")

p +   
  grid.brackets(x1 = 100, y1 = 5,   
                x2 = 1,  y2 = 20, lwd = 2, col = "black")



  #coord_flip()
  #coord_equal()
#  coord_fixed(ratio = 100)
#mean(S99_10y$rate)
p; plotly::ggplotly(p)  

#ggsave("S99_recid.png", p, width = 11, height = 11) #, dpi = 400

#?geom_line


geom_line(data = ., aes(score, pred_recid))
  
```

