```{r message=FALSE, warning=FALSE, include=FALSE}
# get the number in the file for the experiment
source(here::here("r", "src",  "this_path.R"))
```

---
title: "`r paste0('Juror Risk - Weighted-Average Illusion (Exp ', stringr::str_extract(basename(this_full_path()), "\\d+"), ')')`"
#author: "gcook"
date: "`r Sys.Date()`"
output: html_document
---


```{r message=FALSE, warning=FALSE, include=FALSE}
suppressWarnings(
  lapply(
    c("data", "r", "r/src", "figs", "images", "docs", "api", "output"),
    FUN = function(x) {
      #if (!dir.exists(here::here(x))) {
        dir.create(here::here(x))
     # }
    }
  ) 
)

################################################################
################################################################
#here::here()
source(here::here("r", "src",  "libraries.R"))
source(here::here("r", "src",  "functions.txt"))
source(here::here("r", "src",  "true_count.R"))
source(here::here("r", "src",  "mode.R"))
source(here::here("r", "src",  "count_to_prop.R"))
source(here::here("r", "src",  "kbl_it_table.R"))
source(here::here("r", "src",  "glm_modPlot.R"))
source(here::here("r", "src",  "data_summary.R"))

setwd(here::here("r")) # someplace this is being overwritten so I'm setting it to r dir to prevent knit error.


#rm(list = ls(all.names = TRUE))      # remove objects in R


proj_name = basename(here::here())
proj_dir <- here::here()
r_dir    <- here::here("r") 
data_dir <- here::here("data") 
include_plots = F
do_exclusion  = F
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

Get Data

```{r message=FALSE, warning=FALSE, include=FALSE}
# get the blais and brent data
source(here::here("r", "src", "blais.R"))

# Read data
source(here::here("r", "src",  "read_data.R"))
#C <- readr::read_csv(here::here("data", "wai_juror_exp2.csv"))
C <- readr::read_csv(here::here("data", 
                                gsub(".Rmd", ".csv", basename(this_full_path()))
                                ))
#source("https://www.dropbox.com/s/rh2vx2s38b6s3xx/setupR.txt?raw=1")                 # get personal functions
```

A summary of Risk Entries

```{r}
mode(C$RiskEntry)

hist(C$AvgScore_Risk_Est_Diff, 
     main = paste("mean = ", round(
       mean(na.omit(C$AvgScore_Risk_Est_Diff)), 2)))


C %>%
  #dplyr::filter(., Exp == "Exp 1") %>%
  dplyr::group_by(., Plot) %>%
  dplyr::summarise(., 
    n = dplyr::n(),
    Mean_Failed_a_Check = round(mean(na.omit(FailedChecks)),2),
    n_RiskEntry_Corr  = sum(ifelse(RiskEntry == 9, 1, 0)),
#    Min_RiskCheck  = max(na.omit(RiskCheck)),
#    Max_RiskCheck  = max(na.omit(RiskCheck)),
    Min_RiskEntry  = max(na.omit(RiskEntry)),
    Max_RiskEntry  = max(na.omit(RiskEntry)),
    Mean_OrderedRisk = round(mean(na.omit(OrderedRisk)),2),
    ) %>% t() %>% 
  kbl_it(caption = "Min and Max Risk Entry by Condition")
```


Attention Checks

```{r message=FALSE, warning=FALSE}
#############################################################
#### Data Summary ###########################################
#############################################################
C %>%
  #dplyr::filter(., tolower(Crime) == "sexual offense") %>%
  #dplyr::filter(., RiskEntry == 9) %>%
  #dplyr::group_by(., RiskEntry) %>%
#  dplyr::filter(., Exp == "Exp 1") %>%
  dplyr::mutate(., CrimeCorr = ifelse(
    tolower(Crime) == "sexual offense", 1, 0)
    ) %>%
  means1(., CrimeCorr ~ Plot + RiskEntry) %>% 
  dplyr::select(., Plot, RiskEntry, n, CrimeCorr) %>% #t() %>% 
  kbl_it(
    caption = "Attention Check: Mean Correct Crime As a Function of Plot and 'RiskEntry' (9 is correct) ")
```

Removing the 

```{r message=FALSE, warning=FALSE}

#C %>%
#  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
#  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
#  dplyr::filter(., RiskEntry == 9) %>%
#  dplyr::filter(., !is.na(JuryJudge)) %>%
#  #dplyr::filter(., exclusion == "include") %>% 
#  dim()

C %>%
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  dplyr::group_by(., Plot) %>%
  dplyr::summarise(.,
                   n = dplyr::n(),
                   RiskEntry_mean = mean(RiskEntry),
                   RiskEntry_med  = median(RiskEntry),
                   RiskEntry_min  = min(RiskEntry),
                   RiskEntry_max  = max(RiskEntry),
                   ) %>% #t() %>% 
  kbl_it(caption = "Attention Check: Mean Reported Risk Entry (both acc and inacc)")
  #means1(., RiskEntry ~ Plot + RiskEntry) %>% 
  #dplyr::select(., Plot, n, RiskEntry, mdn, min, max) %>% t() %>% 
 

###############################################################################
# Estimate scatterplot for average of all Static-99R
# They don't yet know the Actual Data
###############################################################################
C %>%
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  means1(., AvgScore_Risk ~ Plot) %>%
  dplyr::select(., Plot, n, AvgScore_Risk, mdn, min, max, skew) %>%
  #select(., -mean) %>% 
  t() %>% kbl_it(caption = 
      "Mean Scatterplot Estimate for all Static-99R Scores")


C %>%
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  dplyr::select(., Plot, AvgScore_Risk) %>%
  dplyr::filter(., Plot != "None") %>% #view()
  #chisq.test(AvgScore_Risk, C$Plot) 
  t.test(as.numeric(AvgScore_Risk) ~ Plot, paired = F, data = .)

C %>%
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  dplyr::select(., Plot, AvgScore_Risk) %>%
  dplyr::filter(., Plot != "None") %>%
  dplyr::mutate(., Plot_fact = as.factor(Plot)) %>%
  coin::median_test(formula = AvgScore_Risk ~ Plot_fact, 
                    data = .)
  
C %>%
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  dplyr::select(., Plot, AvgScore_Risk) %>%
  dplyr::filter(., Plot != "None") %>% #view()
  dplyr::mutate(., Plot = as.factor(Plot)) %>%
  coin::wilcox_test(formula = AvgScore_Risk ~ Plot, 
                    data = ., distribution = "exact", 
                    conf.int = T)
  
t_obs <- C %>%
    dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  dplyr::select(., Plot, AvgScore_Risk) %>%
  dplyr::filter(., Plot != "None") %>%
  infer::specify(AvgScore_Risk ~ Plot, x = .) %>%
  infer::calculate(stat = "diff in means", 
                   order = c("Unweighted", "Weighted"))

C %>%
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  dplyr::select(., Plot, AvgScore_Risk) %>%
  dplyr::filter(., Plot != "None") %>%
  infer::specify(AvgScore_Risk ~ Plot, x = .) %>%
  infer::hypothesize(null = "independence") %>%
  infer::generate(reps = 1000, type = "permute") %>%
  infer::calculate(stat = "diff in means", 
                   order = c("Unweighted", "Weighted")) %>%
  infer::visualize() + 
  infer::shade_p_value(t_obs, direction = "two-sided")
```


```{r}
C %>%
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  ggplot(., aes(x = AvgScore_Risk, fill = Plot)) +
  geom_density(alpha = 0.5) + theme_minimal() 


##########################################################################
# Estimate scatterplot for Static-99R for the defendant
# They don't yet know the Actual Data
##########################################################################
C %>%
    dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  dplyr::filter(., RiskEntry == 9) %>%
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  means1(., Score_Risk ~ Plot) %>% 
  dplyr::select(., Plot, n, mean, mdn, min, max, skew) %>%
  #select(., -Score_Risk) %>% 
  t() %>% kbl_it(caption = 
    "Mean Scatterplot Estimate for Defendant's Static-99R Score")
```

Juror Commitment Decisions

```{r}
# Juror Decision
C %>% 
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>% 
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  #dplyr::select(., Plot, JuryJudge) %>% view()
  dplyr::group_by(., Plot) %>%
  dplyr::summarise(., 
            n = dplyr::n(),
            yes = sum(JuryJudge, na.rm = T),
            mean = yes/n) %>% t() %>% 
  kbl_it(caption = "Commitment Decisions by Condition")

C %>%
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  means1(., JuryJudge ~ Plot) %>% 
  dplyr::select(., Plot, n, mean, mdn, min, max, skew) %>% t() %>%
  kbl_it(
    caption = "Commitment Decisions by Condition")

# the numeric estimates for risk levels


C %>%
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  #means1(., JuryJudge ~ Plot) %>% 
  #select(., Plot, n, mean, mdn, min, max, skew) %>%
  #rename(.data, Commit = mean) #%>%
  data_summary(., varname = "JuryJudge", groupnames = c("Plot")) +
  ggplot(., aes(x = Plot, y = JuryJudge)) + 
  geom_bar(stat = "identity", 
           #color = "black", 
           position = position_dodge()
           ) + 
  #geom_errorbar(aes(ymin = JuryJudge-sd, ymax=JuryJudge+sd),width = .2,position = position_dodge(.9)) +
  scale_y_continuous(limits = c(0.0, 0.5), n.breaks = 10) + 
  labs(y = "Commitment Decision\n (% Yes)", 
       x = "Plot Communication Format") +
  theme_classic() 

base_commit_plot <- C %>%  
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  #means1(., JuryJudge ~ Plot) %>% 
  #select(., Plot, n, mean, mdn, min, max, skew) %>%
  #rename(.data, Commit = mean) #%>%
  data_summary(., varname = "JuryJudge", groupnames = c("Plot")) %>%
  ggplot(., aes(x = Plot, y = JuryJudge))

base_commit_plot + geom_pointrange(aes(ymin = JuryJudge-sd, ymax = JuryJudge+sd))

base_commit_plot + geom_linerange(aes(ymin = JuryJudge-sd, ymax = JuryJudge+sd))


C %>%  
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  means1(., JuryJudge ~ Plot) %>% 
  select(., Plot, n, mean, mdn, min, max, skew) %>%
  #rename(.data, Commit = mean) #%>%
  ggplot(., aes(x = Plot, y = mean)) +
  geom_bar(stat = "identity") + #ymin = mean-se, ymax = mean+se)) +
  theme_ben()
  

```

MinNumEst

```{r}
C %>%
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  dplyr::group_by(., Plot) %>%
  dplyr::summarise(.,
                   MinNum_BRD = mean(MinNumEst),
                   #MinCat_BRD = mean(MinNumEst_2),
                   ) %>%
   kbl_it(
    caption = "Minimum Recidivism Risk Estimate for Beyond Reasonable Doubt")
  

C <- C %>%
  dplyr::mutate(., MinNumEst_2 = gsub(" Risk", "", MinNumEst_2)) %>%
  dplyr::mutate(., MinCat_BRD = factor(
    MinNumEst_2, levels = c("Very Low", 
                            "Below Average",
                            "Average", 
                            "Above Average",
                            "Well Above Average"))
  ) %>% 
  dplyr::mutate(., MinCat_BRD_num = case_when(
    MinCat_BRD == "Very Low" ~ 1,
    MinCat_BRD == "Below Average" ~ 2,
    MinCat_BRD == "Average" ~ 3,
    MinCat_BRD == "Above Average" ~ 4,
    MinCat_BRD == "Well Above Average" ~ 5,
  ))

C %>%
  select(., Plot, MinNumEst, MinCat_BRD_num) %>%
  group_by(., Plot) %>%
  summarize(., corr = cor(MinNumEst, MinCat_BRD_num, 
                          method = "kendall")) %>% 
  kbl_it(caption = "Kendall Correlation 'MinNumEst & MinCat_BRD_num'")
  

#C %>% count_2_prop(data = ., "Plot", "MinCat_BRD")

C %>%
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  count_to_prop(data = ., "Plot", "MinCat_BRD") %>%
  ggplot(data = ., 
         aes(x = Plot, y = prop)) +
  geom_bar(aes(fill = Plot), colour = "black", 
           width = .8, stat = "identity"#, position = "stack"
      ) + coord_flip() + 
  geom_text(aes(x = Plot, 
                y = prop,
                label = round(prop,2)
                #label = paste0(round(prop,2), " (", round(perc, 1),"%)")
                , hjust = +1
                         
                         )) +
  facet_wrap(~Plot) + theme_classic() + 
  theme(legend.position = "none") +
  ggtitle("Minimum Recidivism Risk Category for Beyond Reasonable Doubt")

```

Main Plot: Risk Estimates by Plot Communication

```{r}
C %>%
  dplyr::select(., starts_with("RiskNumEst_"))

mean_Levels <- C %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  dplyr::group_by(., Plot) %>%
  dplyr::summarise(., across(starts_with(
    "RiskNumEst_"), ~mean(.x, na.rm = T), .names = "{.col}")) %>%
  tidyr::pivot_longer(
    cols = c(RiskNumEst_1, RiskNumEst_2,
             RiskNumEst_3, RiskNumEst_4, RiskNumEst_5), 
    names_to = "Level", 
    values_to = "Risk"
  ) %>% 
  dplyr::mutate(., Level = gsub("RiskNumEst_", "", Level)) %>%
  dplyr::select(., c(Plot, Level, Risk))

summary_Levels <- C %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  dplyr::select(., c(id, Plot, 
                     RiskNumEst_1, RiskNumEst_2, RiskNumEst_3, 
                     RiskNumEst_4, RiskNumEst_5)) %>%
  tidyr::pivot_longer(
    cols = c(RiskNumEst_1, RiskNumEst_2, RiskNumEst_3,
             RiskNumEst_4, RiskNumEst_5), 
    names_to = "Level", 
    values_to = "Risk"
  ) %>% 
  dplyr::group_by(., Plot, Level) %>%
  dplyr::summarise(., 
            #Risk = mean(na.omit(Risk)),
            Risk = median(na.omit(Risk)) 
            ) %>%
  dplyr::mutate(., Level = gsub("RiskNumEst_", "", Level))

n_Plot <- C %>%
  dplyr::filter(., Exp == "Exp 1") %>%
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  dplyr::group_by(., Plot) %>%
  summarise(., n = dplyr::n()
            ) 
#n_Plot

  # plot with ids
x_labels <- c("Well Below Avg.", "Below Avg.", "Average", "Above Avg.", "Well Above Avg.")
cols <- c("black", "blue", "green")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cols <- c("#56B4E9", "#009E73", "#CC79A7")
cols <- c("#0072B2", "#E69F00", "#D55E00")
cols <- c("grey", "red", "blue")
cols <- c("#737373", "#FA2D56", "#2D7FFA") #  "#96B3F2", "#F27981")
# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73",
                "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


#C %>%
#  filter(., exclusion == "include") %>%
#  select(., id, RiskNumEst_1, RiskNumEst_2, RiskNumEst_3,
#         RiskNumEst_4, MinNumEst, MinNumEst_2, MinNumEst_3) %>%
#  view()

risk_plot_exp1 <- C %>%
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  #dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  #dplyr::filter(., exclusion == "include") %>%
  #dplyr::filter(., Plot %in% c("None")) %>%
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  dplyr::mutate(., id = seq(1, length(id))) %>%
  dplyr::select(., -Risk) %>%
  dplyr::filter(., RiskNumEst_1 < 90) %>%
  tidyr::pivot_longer(
    cols = c(RiskNumEst_1, RiskNumEst_2, RiskNumEst_3,
             RiskNumEst_4, RiskNumEst_5), 
    names_to = "Level", 
    values_to = "Risk"
  ) %>% 
  dplyr::mutate(., Level = gsub("RiskNumEst_", "", Level)) %>%
  dplyr::select(., c(id, Plot, Level, Risk)) %>% 
  #group_by(., Plot) %>%
  #mutate(., Level = gsub("RiskNumEst_", "", Level)) %>%
  ggplot(., aes(x = Level, y = Risk, color = Plot)
         ) +
  #geom_line() + 
  geom_jitter(width = .2, height = 1.5, size = 1.5,
              alpha = .5, 
              #shape = 21#,
              #aes(color = Plot)
              ) #+ 
  #geom_line(inherit.aes = T, 
  #          aes(group = id), 
  #          position = position_jitter(seed = 1), 
  #          size = .4, linetype = 2, alpha = 0.8) +
  # the group level line and points

risk_plot_mean <- risk_plot_exp1 + 
  geom_point(data = mean_Levels, inherit.aes = F, 
             alpha = .8, size = 4, shape = 21, 
             aes(x = Level, y = Risk, 
                 #group = Plot, 
                 fill  = Plot), 
             #fill = Plot, #rep(cols,4), 
             color = "black", 
             ) +  
  geom_line(data = mean_Levels, inherit.aes = F, 
            alpha = .5, size = 1.5, #linetype = 4,
            aes(x = Level, y = Risk, 
                group = Plot, 
                color = Plot,
                )
            ) #+
  #scale_color_manual(values = cols) +
  #ggrepel::geom_text_repel(max.overlaps = 100, aes(label = id), size = 3, color = "gray", segment.colour = NA) +

risk_plot_median <- risk_plot_exp1 + 
  geom_point(data = summary_Levels, inherit.aes = F, 
             alpha = .8, size = 4, shape = 21, 
             aes(x = Level, y = Risk, 
                 #group = Plot, 
                 fill  = Plot), 
             #fill = Plot, #rep(cols,4), 
             color = "black", 
             ) +  
  geom_line(data = summary_Levels, inherit.aes = F, 
            alpha = .5, size = 1.5, #linetype = 4,
            aes(x = Level, y = Risk, 
                group = Plot, 
                color = Plot,
                )
            ) #+


risk_plot_mean <- risk_plot_mean +  
  labs(fill = 'Plot',
       y = "Minimum Risk Percentage\n (mean)",
       x = "Categorical Risk Label") +
  scale_x_discrete(labels = x_labels) +
  scale_y_continuous(n.breaks = 20, limits = c(5, 90)) +
  theme_classic() +
  theme(axis.line = 
          element_line(colour = "black", 
                       size = 1, linetype = "solid"),
        axis.title = element_text(size = 14, face = "bold"), 
        axis.text  = element_text(size = 14),
        strip.text.y = element_text(size = 12),
        aspect.ratio = 1/1,
  #      legend.position = "none"
  ) + 
  scale_color_manual(values = cols) +
  scale_fill_manual(values = cols) 

risk_plot_median <- risk_plot_median +  
  labs(fill = 'Plot',
       y = "Minimum Risk Percentage\n (median)",
       x = "Categorical Risk Label") +
  scale_x_discrete(labels = x_labels) +
  scale_y_continuous(n.breaks = 20, limits = c(5, 90)) +
  theme_classic() +
  theme(axis.line = 
          element_line(colour = "black", 
                       size = 1, linetype = "solid"),
        axis.title = element_text(size = 14, face = "bold"), 
        axis.text  = element_text(size = 14),
        strip.text.y = element_text(size = 12),
        aspect.ratio = 1/1,
  #      legend.position = "none"
  ) + 
  scale_color_manual(values = cols) +
  scale_fill_manual(values = cols) 

  #scale_fill_manual('Legend Title', 
  #                  values = c('gray', 'green', "blue")
  #                  )
```


```{r}
risk_plot_mean
```

```{r}
risk_plot_median
```

```{r}
gridExtra::grid.arrange(risk_plot_mean, risk_plot_median, ncol = 2)
```

```{r}
C %>%
  #dplyr::filter(., FailedChecks == 0) %>%  # keep no failed checks
  dplyr::filter(., OrderedRisk  == 1) %>% # keep ordered risk
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  ggplot(., aes(x = RiskNumEst_1, fill = Plot)) +
  geom_density(alpha = 0.5) + theme_minimal() 


#C %>%
 # dplyr::filter(., Plot == "None") %>%
#hist(C[Plot == "None", "RiskNumEst_1"], breaks = 20)

  #summarise(., across(where(is.numeric), ~ mean(.x, na.rm = TRUE), .names = "{.col}"))


C %>% 
  dplyr::filter(., CrimeAcc == 1) %>%   # correct crime
  dplyr::filter(., RiskEntry == 9) %>%  # correct risk reported
  dplyr::filter(., !is.na(JuryJudge)) %>%
  #dplyr::filter(., exclusion == "include") %>%
  means1(., RiskNumEst_1 ~ Plot) %>% kbl_it(
    caption = "Commitment Decisions by Condition")

C %>% 
  dplyr::filter(., exclusion == "include") %>%
  means1(., RiskNumEst_2 ~ Plot) %>% kbl_it(
    caption = "Commitment Decisions by Condition")

C %>% 
  dplyr::filter(., exclusion == "include") %>%
  means1(., RiskNumEst_3 ~ Plot) %>% kbl_it(
    caption = "Commitment Decisions by Condition")

C %>% 
  dplyr::filter(., exclusion == "include") %>%
  means1(., RiskNumEst_4 ~ Plot) %>% kbl_it(
    caption = "Commitment Decisions by Condition")

C %>%
  #dplyr::filter(., Exp == "Exp 1") %>%
  means1(., RiskNumEst_5 ~ Plot) %>% 
  kbl_it(
    caption = "Commitment Decisions by Condition")
```


